### ISSUE TITLE
Files don't open in most recently used window and does not bring Atom to the foreground

### ISSUE THREAD

**Issue by mafredri** [randy3k/remote-atom#22]
When I have multiple Atom windows open, files keep opening in the first, not the most recently used one. Opening a file does also not bring Atom to the foreground. This is quite annoying and often results in the user (me) believing remote-atom isn't working.

**Comment by randy3k** [comment]
It should be fixed now.

**Comment by mafredri** [comment]
Thanks for the prompt fix! It definitely fixes the issue of focusing atom, but it still doesn't open in the most recently active window, no matter what I do it keeps opening in one specific Atom window.

**Comment by randy3k** [comment]
Atom windows do not communicate as far as I know, [see](https://discuss.atom.io/t/how-can-i-open-a-panel-in-a-new-window/20635). Each window is a new process, there are not easy ways to tell another window (the active window) to do something, for example, opening a file. I am afraid that the second issue is unfixable, unless for the moment.

**Comment by mafredri** [comment]
I see, thanks for the explanation! It's a shame that Atom doesn't support this, one can hope that it gets better down the road.

Anyway, this new focus feature makes it so much better already, thanks a lot for the plugin!

**Comment by randy3k** [comment]
:)
